from evennia import Command
from evennia.utils.create import create_object
from typeclasses.characters import Character

class CmdAdminChargenTest(Command):
    """
    Admin: Instantly create a test character with all stats set to max.
    Usage:
        adminchargentest <name>
    """
    key = "adminchargentest"
    locks = "cmd:perm(Builder)"
    help_category = "Admin"

    def func(self):
        caller = self.caller
        if not self.args:
            caller.msg("Usage: adminchargentest <name> [body=8 reflexes=7 dexterity=10 technique=9 smarts=8 willpower=10 edge=8 empathy=8]")
            return
        parts = self.args.split()
        name = parts[0]
        stat_defaults = {
            "body": 1,
            "reflexes": 1,
            "dexterity": 1,
            "technique": 1,
            "smarts": 1,
            "willpower": 1,
            "edge": 1,
            "empathy": 1
        }
        stat_values = stat_defaults.copy()
        for part in parts[1:]:
            if "=" in part:
                key, val = part.split("=", 1)
                key = key.lower()
                if key in stat_values:
                    try:
                        stat_values[key] = int(val)
                    except ValueError:
                        caller.msg(f"Invalid value for {key}: {val}")
                        return
        char = create_object(Character, key=name, location=caller.location, home=caller.location)
        char.db.body = stat_values["body"]
        char.db.reflexes = stat_values["reflexes"]
        char.db.dexterity = stat_values["dexterity"]
        char.db.technique = stat_values["technique"]
        char.db.smarts = stat_values["smarts"]
        char.db.willpower = stat_values["willpower"]
        char.db.edge = stat_values["edge"]
        char.db.empathy = stat_values["empathy"]
        char.db.desc = "Test character generated by adminchargentest."
        char.tags.add("admin_test")
        stat_str = ", ".join(f"{k}={v}" for k, v in stat_values.items())
        caller.msg(f"Created test character: {char.key} with stats: {stat_str}")
